### ISSUE TITLE
HerbASAP not working with latest macOS (11, Big Sur)?

### ISSUE THREAD

**Issue by bgq527** [CapPow/HerbASAP#57]
Currently, it is not able to properly open settings wizard, opening with a blank screen. Note that this is on a Hackintosh.
@j-h-m If you have a real Mac with Big Sur, can you go ahead and try this?

System Specs:
macOS 11.0.1 Big Sur on OpenCore 0.6.3
Intel Core i7-8550U
Python 3.7
Using requirements.txt for libraries
Already tried headless version of OpenCV, didn't work.

SMBIOS is MacBookPro15,2:
![image](https://user-images.githubusercontent.com/37383659/100528711-8ecf8500-31ad-11eb-97e9-834897a20299.png)

**Comment by j-h-m** [comment]
Hey @bgq527,

Yes I just updated my Macbook to Big Sur so I will give it a try.

**Comment by bgq527** [comment]
Update, was able to fix it - just update to the latest version of PyQt5 and PyQt5-sip (currently version 5.12.3).

`pip install -U PyQt5`

@j-h-m will wait for confirmation whether or not that works and then I'll close it

**Comment by j-h-m** [comment]
Confirmed: I had the same issue, but the update fixed it.

**Comment by dakilaledesma** [comment]
Fixed with a new version of requirements.txt in this commit: 65b2819e88d7b87d8be928e935637ac54aa7a7c5
